// <auto-generated />
using System;
using Day12Test.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day12Test.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230321094332_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Day12Test.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KmRace")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RaceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceDestination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RaceId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("Day12Test.Models.Taxi", b =>
                {
                    b.Property<int>("TaxiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBusy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberRaces")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxiName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaxiId");

                    b.ToTable("Taxi");
                });
#pragma warning restore 612, 618
        }
    }
}
