// <auto-generated />
using System;
using Day13Lab2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day13Lab2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230324133913_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Day13Lab2.Models.Humidity", b =>
                {
                    b.Property<int>("HumidityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("HumidityID");

                    b.ToTable("Humidity");
                });

            modelBuilder.Entity("Day13Lab2.Models.Temperature", b =>
                {
                    b.Property<int>("TemperatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TemperatureDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("TemperatureValue")
                        .HasColumnType("REAL");

                    b.Property<int>("ZoneID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TemperatureID");

                    b.HasIndex("ZoneID");

                    b.ToTable("Temperatures");
                });

            modelBuilder.Entity("Day13Lab2.Models.Zone", b =>
                {
                    b.Property<int>("ZoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HumidityID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<float>("TargetTemperature")
                        .HasColumnType("REAL");

                    b.HasKey("ZoneID");

                    b.HasIndex("HumidityID");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Day13Lab2.Models.Temperature", b =>
                {
                    b.HasOne("Day13Lab2.Models.Zone", "Zone")
                        .WithMany("Rilevazioni")
                        .HasForeignKey("ZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Day13Lab2.Models.Zone", b =>
                {
                    b.HasOne("Day13Lab2.Models.Humidity", "Humidity")
                        .WithMany("Zones")
                        .HasForeignKey("HumidityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Humidity");
                });

            modelBuilder.Entity("Day13Lab2.Models.Humidity", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("Day13Lab2.Models.Zone", b =>
                {
                    b.Navigation("Rilevazioni");
                });
#pragma warning restore 612, 618
        }
    }
}
